better build process
Signed-off-by: Platan Drizzleword <drizzleword@outlook.com>

diff --git a/bin/runag b/bin/runag
--- a/bin/runag
+++ b/bin/runag
@@ -24,61 +24,62 @@ if [ "${BASH_SOURCE[0]}" = "$0" ]; then
   fi
   set -o nounset
 fi
-
 # END set_shell_options
 
 # BEGIN load_runag_library
 
 runag::load_runag_library() {
+  local self_path
+  local lib_dir
+  local file_path
+
   # resolve symlink if needed
   if [ -L "${BASH_SOURCE[0]}" ]; then
-    local bin_path; bin_path="$(readlink -f "${BASH_SOURCE[0]}")" || { echo "Unable to readlink '${BASH_SOURCE[0]}' ($?)" >&2; return 1; }
+    self_path="$(readlink -f "${BASH_SOURCE[0]}")" || { echo "Unable to resolve symlink ${BASH_SOURCE[0]} ($?)" >&2; return 1; }
   else
-    local bin_path; bin_path="${BASH_SOURCE[0]}"
+    self_path="${BASH_SOURCE[0]}"
   fi
 
-  # get basename of binary
-  local bin_name; bin_name="$(basename "${bin_path}")" || { echo "Unable to get a basename of '${bin_path}' ($?)" >&2; return 1; }
+  # get dirname
+  lib_dir="$(dirname "${self_path}")/$1" || { echo "Unable to get a dirname of ${self_path} ($?)" >&2; return 1; }
 
-  # get dirname that yet may result to relative path
-  local unresolved_bin_dir; unresolved_bin_dir="$(dirname "${bin_path}")" || { echo "Unable to get a dirname of '${bin_path}' ($?)" >&2; return 1; }
+  # check if lib dir exists
+  test -d "${lib_dir}" || { echo "Unable to find rùnag library directory ${lib_dir}" >&2; return 1; }
 
-  # get absolute path to dirname
-  local bin_dir; bin_dir="$(cd "${unresolved_bin_dir}" >/dev/null 2>&1 && pwd)" || { echo "Unable to determine absolute path for '${unresolved_bin_dir}' ($?)" >&2; return 1; }
-
-  # set RUNAG_BIN_PATH if needed
-  if [ -z "${RUNAG_BIN_PATH:-}" ] && [ -f "${bin_dir}/${bin_name}" ] && [ -x "${bin_dir}/${bin_name}" ]; then
-    export RUNAG_BIN_PATH="${bin_dir}/${bin_name}"
-  fi
-
-  . "${bin_dir}/../index.sh" || { echo "Unable to load '${bin_dir}/../index.sh' ($?)" >&2; return 1; }
+  # load library files
+  for file_path in "${lib_dir}"/*.sh; do
+    if [ -f "${file_path}" ]; then
+      . "${file_path}" || { echo "Unable to load ${file_path} ($?)" >&2; return 1; }
+    fi
+  done
 }
 
-# Load rùnag library index file
-runag::load_runag_library || {
-  echo "Unable to load rùnag library index file ($?)" >&2
+# Load rùnag library
+runag::load_runag_library "../lib" || {
+  echo "Unable to load rùnag library ($?)" >&2
   if [ "${BASH_SOURCE[0]}" != "$0" ]; then
     return 1 # use return if we are sourced
   else
     exit 1 # use exit if not
   fi
 }
-
 # END load_runag_library
 
 # BEGIN invoke_runagfile
 
 # == we should have all library functions available by now ==
 
-# I don't use "user-function || fail" here in case if someone wants to use "set -o errexit" in their functions that I may call here
-
 # Load rùnagfile
-if [ "${BASH_SOURCE[0]}" != "$0" ]; then # we are sourced
-  runagfile::load
-  softfail --unless-good --exit-status $? "Unable to load rùnagfile ($?)" || return $?
-else # we are not sourced
-  runagfile::load
-  softfail --unless-good --exit-status $? "Unable to load rùnagfile ($?)" || exit $?
+if [ "${1:-}" == "--skip-runagfile-load" ]; then
+  shift
+else
+  if [ "${BASH_SOURCE[0]}" != "$0" ]; then # we are sourced
+    runagfile::load
+    softfail --unless-good --exit-status $? "Unable to load rùnagfile ($?)" || return $?
+  else # we are not sourced
+    runagfile::load
+    softfail --unless-good --exit-status $? "Unable to load rùnagfile ($?)" || exit $?
+  fi
 fi
 
 # if there is something in the first argument, run it
@@ -115,5 +116,4 @@ if [ "${BASH_SOURCE[0]}" = "$0" ]; then
   log::error "Please specify a function name or command to run, or define a runagfile::main, or add one or more items to runag_menu to see it if you run rùnag in terminal"
   exit 1
 fi
-
 # END invoke_runagfile
