error handling, better menu

diff --git a/bin/sopka b/bin/sopka
--- a/bin/sopka
+++ b/bin/sopka
@@ -56,12 +56,15 @@ if [[ "$OSTYPE" =~ ^msys ]]; then
   fi
 fi
 
+# I use "test" instead of "|| fail" here for the case if someone wants to "set -o errexit" in their functions
 if [ -n "${1:-}" ]; then
   declare -f "$1" >/dev/null || fail "Argument must be a function name: $1"
-  "$1" "${@:2}" || fail
+  "$1" "${@:2}"
+  test $? = 0 || fail "Error performing $1"
 else
   if declare -f sopka::menu >/dev/null; then
-    sopka::menu || fail
+    sopka::menu
+    test $? = 0 || fail "Error performing sopka::menu"
   else
     fail "sopka::menu function must be defined"
   fi
