rename to sopka

diff --git a/bin/sopka b/bin/sopka
--- a/bin/sopka
+++ b/bin/sopka
@@ -14,28 +14,37 @@
 #  See the License for the specific language governing permissions and
 #  limitations under the License.
 
+if [ -n "${VERBOSE:-}" ]; then
+  set -o xtrace
+fi
+
+set -o nounset
+
 fail() {
   echo "${BASH_SOURCE[1]}:${BASH_LINENO[0]}: in \`${FUNCNAME[1]}': Error: ${1:-"Abnormal termination"}" >&2
   exit "${2:-1}"
 }
 
 SOPKA_SRC_DIR="$(dirname "${BASH_SOURCE[0]}")" || fail "Unable to determine SOPKA_SRC_DIR ($?)"
-SOPKA_SRC_DIR="$(cd "${SOPKA_SRC_DIR}" >/dev/null 2>&1 && pwd)" || fail "Unable to determine full path for SOPKA_SRC_DIR ($?)"
+SOPKA_SRC_DIR="$(cd "${SOPKA_SRC_DIR}"/.. >/dev/null 2>&1 && pwd)" || fail "Unable to determine full path for SOPKA_SRC_DIR ($?)"
 
 export SOPKA_SRC_DIR
 
-. "${SOPKA_SRC_DIR}/lib/benchmark.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/bitwarden.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/config-files.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/fs.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/git.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/github.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/macos.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/nodejs.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/ruby.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/shellrcd-files.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/shellrcd.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/ssh.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/tools.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/ubuntu-packages.sh" || fail
-. "${SOPKA_SRC_DIR}/lib/ubuntu.sh" || fail
+. "${SOPKA_SRC_DIR}/index.sh" || fail
+
+if [ -f "./sopka.sh" ]; then
+  SOPKA_DIR="$(pwd)" || fail
+  export SOPKA_DIR
+  . "./sopka.sh" || fail
+elif [ -f "${HOME}/.sopka/index.sh" ]; then
+  export SOPKA_DIR="${HOME}/.sopka"
+  . "${HOME}/.sopka/index.sh" || fail
+else
+  fail "Unable to find ./sopka.sh or ${HOME}/.sopka/index.sh"
+fi
+
+if [ -n "${1:-}" ]; then
+  declare -f "$1" >/dev/null || fail "Argument must be a function name: $1"
+fi
+
+"${1:-sopka::menu}" "${@:2}" || fail
