better bin/sopka run modes

diff --git a/bin/sopka b/bin/sopka
--- a/bin/sopka
+++ b/bin/sopka
@@ -99,23 +99,19 @@ else
 fi
 
 # run function provided in first argument, or run sopkafile::main, if defined
-#
 # I use "test" instead of "|| fail" here for the case if someone wants to
 # "set -o errexit" in their functions
-
-if [ "${0:0:1}" = "-" ] || [ "$0" = "-bash" ] || [ "$0" = "bash" ]; then
-  return
-fi
-
-if [ "$(basename "$0")" = "sopka" ]; then
-  if [ -n "${1:-}" ]; then
-    declare -f "$1" >/dev/null || fail "Argument must be a function name: $1"
-    "$1" "${@:2}"
-    test $? = 0 || fail "Error performing $1"
-  elif declare -f sopkafile::main >/dev/null; then
-    sopkafile::main
-    test $? = 0 || fail "Error performing sopkafile::main"
-  else
-    fail "please specify a function name to run, or define a sopkafile::main"
+if [ -n "${1:-}" ]; then
+  declare -f "$1" >/dev/null || fail "Argument must be a function name: $1"
+  "$1" "${@:2}"
+  test $? = 0 || fail "Error performing $1"
+else
+  if [ "${0:0:1}" != "-" ] && [ "$(basename "$0")" = "sopka" ]; then
+    if declare -f sopkafile::main >/dev/null; then
+      sopkafile::main
+      test $? = 0 || fail "Error performing sopkafile::main"
+    else
+      fail "please specify a function name to run, or define a sopkafile::main"
+    fi
   fi
 fi
