. sopka

diff --git a/bin/sopka b/bin/sopka
--- a/bin/sopka
+++ b/bin/sopka
@@ -95,15 +95,17 @@ fi
 # I use "test" instead of "|| fail" here for the case if someone wants to
 # "set -o errexit" in their functions
 
-if [ "$0" != "-bash" ]; then
-  if [ -n "${1:-}" ]; then
-    declare -f "$1" >/dev/null || fail "Argument must be a function name: $1"
-    "$1" "${@:2}"
-    test $? = 0 || fail "Error performing $1"
-  elif declare -f sopkafile::main >/dev/null; then
-    sopkafile::main
-    test $? = 0 || fail "Error performing sopkafile::main"
-  else
-    fail "please specify a function name to run, or define a sopkafile::main"
-  fi
+if [ "$0" = "-bash" ] || [ "$0" = "bash" ]; then
+  return
+fi
+
+if [ -n "${1:-}" ]; then
+  declare -f "$1" >/dev/null || fail "Argument must be a function name: $1"
+  "$1" "${@:2}"
+  test $? = 0 || fail "Error performing $1"
+elif declare -f sopkafile::main >/dev/null; then
+  sopkafile::main
+  test $? = 0 || fail "Error performing sopkafile::main"
+else
+  fail "please specify a function name to run, or define a sopkafile::main"
 fi
