build
Signed-off-by: Stanislav Senotrusov <senotrusov@gmail.com>

diff --git a/bin/ssh-call b/bin/ssh-call
--- a/bin/ssh-call
+++ b/bin/ssh-call
@@ -507,7 +507,26 @@ ssh::call::produce_script ()
             echo "export $(printf "%q=%q" "${env_list_item}" "${!env_list_item}")";
         fi;
     done;
-    if [ "${command_mode}" = false ] && [ "${command_present}" = true ] && declare -F "$1" > /dev/null; then
+    local remote_rc_string;
+    local remote_rc_require_functions=false;
+    if declare -p REMOTE_RC 2> /dev/null | grep -q '^declare \-a'; then
+        if [ "${#REMOTE_RC[@]}" -gt 0 ]; then
+            if declare -F "${REMOTE_RC[0]}" > /dev/null; then
+                remote_rc_require_functions=true;
+            fi;
+            printf -v remote_rc_string " %q" "${REMOTE_RC[@]}" || softfail || return $?;
+            remote_rc_string="${remote_rc_string:1}" || softfail || return $?;
+        fi;
+    else
+        if [ -n "${REMOTE_RC:-}" ]; then
+            remote_rc_require_functions=true;
+            remote_rc_string="${REMOTE_RC}";
+        fi;
+    fi;
+    if [ "${remote_rc_require_functions}" = true ] || { 
+        [ "${command_mode}" = false ] && [ "${command_present}" = true ] && declare -F "$1" > /dev/null
+    }; then
+        echo function dump 1>&2;
         if [ -z "${PS1:-}" ]; then
             declare -f || softfail "Unable to produce source code dump of functions" || return $?;
         else
@@ -528,14 +547,8 @@ ssh::call::produce_script ()
     if [ -n "${REMOTE_UMASK:-}" ]; then
         printf "umask %q || exit \$?\n" "${REMOTE_UMASK}";
     fi;
-    if declare -p REMOTE_RC 2> /dev/null | grep -q '^declare \-a'; then
-        local rc_string;
-        printf -v rc_string " %q" "${REMOTE_RC[@]}" || softfail || return $?;
-        printf "{\n%s\n} || { exit_status=\$?; echo 'Error performing REMOTE_RC line' >&2; exit \$?; }\n" "${rc_string:1}" || softfail || return $?;
-    else
-        if [ -n "${REMOTE_RC:-}" ]; then
-            printf "{\n%s\n} || { exit_status=\$?; echo 'Error performing REMOTE_RC line' >&2; exit \$?; }\n" "${REMOTE_RC}" || softfail || return $?;
-        fi;
+    if [ -n "${remote_rc_string:-}" ]; then
+        printf "{\n%s\n} || { exit_status=\$?; echo 'Error performing REMOTE_RC line' >&2; exit \$?; }\n" "${remote_rc_string}" || softfail || return $?;
     fi;
     if [ "${command_present}" = false ] && [ "${terminal_mode}" = true ]; then
         echo '"${SHELL}"';
