build
Signed-off-by: Stanislav Senotrusov <senotrusov@gmail.com>

diff --git a/bin/ssh-call b/bin/ssh-call
--- a/bin/ssh-call
+++ b/bin/ssh-call
@@ -30,7 +30,7 @@ fail ()
     local trace_start=1;
     local message;
     while [ "$#" -gt 0 ]; do
-        case $1 in 
+        case "$1" in 
             -e | --exit-status)
                 exit_status="$2";
                 shift;
@@ -103,12 +103,21 @@ ssh::call ()
     local keep_temp_files=false;
     local terminal_mode=false;
     while [ "$#" -gt 0 ]; do
-        case $1 in 
+        case "$1" in 
+            --root)
+                local REMOTE_USER=root;
+                shift
+            ;;
+            --user | -l)
+                local REMOTE_USER="$2";
+                shift;
+                shift
+            ;;
             -[46AaCfGgKkMNnqsTtVvXxYy]*)
                 Ssh_Args+=("$1");
                 shift
             ;;
-            -[BbcDEeFIiJLlmOopQRSWw])
+            -[BbcDEeFIiJLmOopQRSWw])
                 Ssh_Args+=("$1" "$2");
                 shift;
                 shift
@@ -166,7 +175,7 @@ ssh::call::internal ()
     local upload_path;
     local ssh_destination;
     while [ "$#" -gt 0 ]; do
-        case $1 in 
+        case "$1" in 
             --absorb)
                 absorb_file="$2";
                 shift;
@@ -391,14 +400,22 @@ ssh::call::internal ()
             fi;
             if [ -s "${temp_dir}/stderr" ]; then
                 if test -t 2; then
-                    printf "setaf 9\nbold" | tput -S 1>&2 2> /dev/null && true;
-                fi;
-                cat "${temp_dir}/stderr" 1>&2 || { 
-                    echo "Unable to display task stderr ($?)" 1>&2;
-                    error_state=true
-                };
-                if test -t 2; then
-                    tput sgr 0 1>&2 2> /dev/null && true;
+                    local error_color;
+                    error_color="$(printf "setaf 9\nbold" | tput -S 2>/dev/null)" || error_color="";
+                    local reset_attrs;
+                    reset_attrs="$(tput sgr 0 2>/dev/null)" || reset_attrs="";
+                    local error_line;
+                    while IFS="" read -r error_line; do
+                        echo "${error_color}${error_line}${reset_attrs}" 1>&2;
+                    done < "${temp_dir}/stderr" || { 
+                        echo "Unable to display task stderr ($?)" 1>&2;
+                        error_state=true
+                    };
+                else
+                    cat "${temp_dir}/stderr" 1>&2 || { 
+                        echo "Unable to display task stderr ($?)" 1>&2;
+                        error_state=true
+                    };
                 fi;
             fi;
             if [ "${error_state}" = true ]; then
@@ -461,7 +478,7 @@ ssh::call::produce_script ()
     local terminal_mode=false;
     local cd_to_home=false;
     while [ "$#" -gt 0 ]; do
-        case $1 in 
+        case "$1" in 
             --command)
                 command_mode=true;
                 shift
@@ -498,8 +515,15 @@ ssh::call::produce_script ()
     if shopt -o -q nounset; then
         echo "set -o nounset";
     fi;
-    local env_list;
-    IFS=" " read -r -a env_list <<< "${REMOTE_ENV:-} RUNAG_VERBOSE" || softfail || return $?;
+    local env_list=();
+    if declare -p REMOTE_ENV 2> /dev/null | grep -q '^declare \-a'; then
+        env_list+=("${REMOTE_ENV[@]}");
+    else
+        if [ -n "${REMOTE_ENV:-}" ]; then
+            IFS=" " read -r -a env_list <<< "${REMOTE_ENV}" || softfail || return $?;
+        fi;
+    fi;
+    env_list+=(RUNAG_VERBOSE);
     local env_list_item;
     for env_list_item in "${env_list[@]}";
     do
@@ -543,6 +567,9 @@ ssh::call::produce_script ()
     if [ -n "${REMOTE_DIR:-}" ]; then
         printf "cd %q || exit \$?\n" "${REMOTE_DIR}";
     fi;
+    if [ -n "${REMOTE_NON_ROOT_UMASK:-}" ]; then
+        printf "if [ \"\${UID}\" != 0 ]; then umask %q || exit \$?; fi\n" "${REMOTE_NON_ROOT_UMASK}";
+    fi;
     if [ -n "${REMOTE_UMASK:-}" ]; then
         printf "umask %q || exit \$?\n" "${REMOTE_UMASK}";
     fi;
@@ -567,7 +594,7 @@ ssh::call::invoke ()
     local nohup_mode=false;
     local terminal_mode;
     while [ "$#" -gt 0 ]; do
-        case $1 in 
+        case "$1" in 
             --nohup)
                 nohup_mode=true;
                 shift
@@ -614,7 +641,7 @@ dir::should_exists ()
     local perhaps_sudo;
     local keep_permissions=false;
     while [ "$#" -gt 0 ]; do
-        case $1 in 
+        case "$1" in 
             -m | --mode)
                 dir_mode="$2";
                 shift;
