ssh::call terminal & direct modes
Signed-off-by: Stanislav Senotrusov <senotrusov@gmail.com>

diff --git a/bin/ssh-call b/bin/ssh-call
--- a/bin/ssh-call
+++ b/bin/ssh-call
@@ -138,7 +138,6 @@ ssh::call ()
     temp_dir="$(mktemp -d)" || softfail "Unable to make temp file" || return $?;
     ssh::call::internal --temp-dir "${temp_dir}" "${internal_args[@]}" "$@";
     local exit_status=$?;
-    softfail --unless-good --exit-status "${exit_status}";
     if [ "${keep_temp_files}" != true ]; then
         rm -fd "${temp_dir}/script" "${temp_dir}/stdin" "${temp_dir}/stdout" "${temp_dir}/stderr" "${temp_dir}" || softfail "Unable to remote temp files";
     fi;
@@ -148,6 +147,7 @@ ssh::call::internal ()
 { 
     local produce_script_args=();
     local direct_mode=false;
+    local terminal_mode=false;
     local keep_temp_files=false;
     local temp_dir;
     local upload_path;
@@ -160,6 +160,10 @@ ssh::call::internal ()
             ;;
             --direct)
                 direct_mode=true;
+                shift
+            ;;
+            --terminal)
+                terminal_mode=true;
                 shift
             ;;
             --keep-temp-files)
@@ -228,144 +232,154 @@ ssh::call::internal ()
     if [ -z "${remote_temp_dir}" ]; then
         softfail "Unable to get remote temp file name" || return $?;
     fi;
-    local remote_stdin_file="/dev/null";
-    if [ ! -t 0 ]; then
-        cat > "${temp_dir}/stdin" || softfail "Unable to read stdin" || return $?;
-        if [ -s "${temp_dir}/stdin" ]; then
-            local stdin_checksum;
-            stdin_checksum="$(cksum <"${temp_dir}/stdin")" || softfail "Unable to get stdin checksum" || return $?;
-            ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'cat >"${temp_dir}/stdin"; if [ "$(cksum <"${temp_dir}/stdin")" != %q ]; then exit 254; fi' "${stdin_checksum}" < "${temp_dir}/stdin" || softfail --exit-status $? "Unable to store stdin data on remote" || return $?;
-            remote_stdin_file="${remote_temp_dir}/stdin";
-        fi;
-    fi;
-    ssh::call::invoke --nohup "${remote_temp_dir}" "${ssh_destination}" 'bash "${temp_dir}/script" <%q >"${temp_dir}/stdout" 2>"${temp_dir}/stderr"; script_status=$?; echo "${script_status}" >"${temp_dir}/exit_status"; touch "${temp_dir}/done"; exit "${script_status}"' "${remote_stdin_file}";
-    local task_status=$?;
-    local task_status_retrieved=false;
-    local stdout_retrieved=false;
-    local stderr_retrieved=false;
-    local call_result;
-    if [ "${task_status}" != 255 ]; then
-        task_status_retrieved=true;
-    fi;
-    local started_at="${SECONDS}";
-    local retry_limit="${REMOTE_RECONNECT_TIME_LIMIT:-600}";
-    local first_run=true;
-    while true; do
-        if [ "${first_run}" = true ]; then
-            first_run=false;
+    if [ "${terminal_mode}" = true ]; then
+        ssh::call::invoke --terminal "${remote_temp_dir}" "${ssh_destination}" 'bash "${temp_dir}/script"';
+        local task_status=$?;
+    else
+        if [ "${direct_mode}" = true ]; then
+            ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'bash "${temp_dir}/script"';
+            local task_status=$?;
         else
-            sleep "${REMOTE_RECONNECT_DELAY:-5}";
-            if [ "$(( SECONDS - started_at ))" -ge "${retry_limit}" ]; then
-                softfail "Unable to obtain task result, maximum time limit reached";
-                return 1;
+            local remote_stdin_file="/dev/null";
+            if [ ! -t 0 ]; then
+                cat > "${temp_dir}/stdin" || softfail "Unable to read stdin" || return $?;
+                if [ -s "${temp_dir}/stdin" ]; then
+                    local stdin_checksum;
+                    stdin_checksum="$(cksum <"${temp_dir}/stdin")" || softfail "Unable to get stdin checksum" || return $?;
+                    ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'cat >"${temp_dir}/stdin"; if [ "$(cksum <"${temp_dir}/stdin")" != %q ]; then exit 254; fi' "${stdin_checksum}" < "${temp_dir}/stdin" || softfail --exit-status $? "Unable to store stdin data on remote" || return $?;
+                    remote_stdin_file="${remote_temp_dir}/stdin";
+                fi;
             fi;
-            log::notice "Attempting to obtain result ($(( retry_limit - (SECONDS - started_at) )) second(s) till timeout)..." 1>&2;
-        fi;
-        if [ "${task_status_retrieved}" = false ]; then
-            ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'test -f "${temp_dir}/done"';
-            call_result=$?;
-            if [ "${call_result}" = 255 ]; then
-                continue;
-            else
-                if [ "${call_result}" != 0 ]; then
-                    ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'test -d "${temp_dir}"';
-                    call_result=$?;
-                    if [ "${call_result}" != 0 ] && [ "${call_result}" != 255 ]; then
-                        softfail "Unable to find remote task state directory, remote host may have been rebooted";
+            ssh::call::invoke --nohup "${remote_temp_dir}" "${ssh_destination}" 'bash "${temp_dir}/script" <%q >"${temp_dir}/stdout" 2>"${temp_dir}/stderr"; script_status=$?; echo "${script_status}" >"${temp_dir}/exit_status"; touch "${temp_dir}/done"; exit "${script_status}"' "${remote_stdin_file}";
+            local task_status=$?;
+            local task_status_retrieved=false;
+            local stdout_retrieved=false;
+            local stderr_retrieved=false;
+            local call_result;
+            if [ "${task_status}" != 255 ]; then
+                task_status_retrieved=true;
+            fi;
+            local started_at="${SECONDS}";
+            local retry_limit="${REMOTE_RECONNECT_TIME_LIMIT:-600}";
+            local first_run=true;
+            while true; do
+                if [ "${first_run}" = true ]; then
+                    first_run=false;
+                else
+                    sleep "${REMOTE_RECONNECT_DELAY:-5}";
+                    if [ "$(( SECONDS - started_at ))" -ge "${retry_limit}" ]; then
+                        softfail "Unable to obtain task result, maximum time limit reached";
                         return 1;
                     fi;
-                    ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'test -f "${temp_dir}/stdout"';
+                    log::notice "Attempting to obtain result ($(( retry_limit - (SECONDS - started_at) )) second(s) till timeout)..." 1>&2;
+                fi;
+                if [ "${task_status_retrieved}" = false ]; then
+                    ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'test -f "${temp_dir}/done"';
                     call_result=$?;
-                    if [ "${call_result}" != 0 ] && [ "${call_result}" != 255 ]; then
-                        softfail "It seems that the remote command did not even start";
-                        return 1;
+                    if [ "${call_result}" = 255 ]; then
+                        continue;
+                    else
+                        if [ "${call_result}" != 0 ]; then
+                            ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'test -d "${temp_dir}"';
+                            call_result=$?;
+                            if [ "${call_result}" != 0 ] && [ "${call_result}" != 255 ]; then
+                                softfail "Unable to find remote task state directory, remote host may have been rebooted";
+                                return 1;
+                            fi;
+                            ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'test -f "${temp_dir}/stdout"';
+                            call_result=$?;
+                            if [ "${call_result}" != 0 ] && [ "${call_result}" != 255 ]; then
+                                softfail "It seems that the remote command did not even start";
+                                return 1;
+                            fi;
+                            continue;
+                        fi;
                     fi;
+                    task_status="$(ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'cat "${temp_dir}/exit_status"')";
+                    call_result=$?;
+                    if [ "${call_result}" = 255 ]; then
+                        continue;
+                    else
+                        if [ "${call_result}" != 0 ]; then
+                            softfail "Unable to obtain exit status from remote";
+                            return 1;
+                        fi;
+                    fi;
+                    if ! [[ "${task_status}" =~ ^[0-9]+$ ]]; then
+                        task_status=1;
+                    fi;
+                    task_status_retrieved=true;
+                fi;
+                if [ "${stdout_retrieved}" = false ]; then
+                    ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'cat "${temp_dir}/stdout"' > "${temp_dir}/stdout";
+                    call_result=$?;
+                    if [ "${call_result}" = 255 ]; then
+                        continue;
+                    else
+                        if [ "${call_result}" != 0 ]; then
+                            softfail "Unable to obtain stdout from remote";
+                            return 1;
+                        fi;
+                    fi;
+                    stdout_retrieved=true;
+                fi;
+                if [ "${stderr_retrieved}" = false ]; then
+                    ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'cat "${temp_dir}/stderr"' > "${temp_dir}/stderr";
+                    call_result=$?;
+                    if [ "${call_result}" = 255 ]; then
+                        continue;
+                    else
+                        if [ "${call_result}" != 0 ]; then
+                            softfail "Unable to obtain stderr from remote";
+                            return 1;
+                        fi;
+                    fi;
+                    stderr_retrieved=true;
+                fi;
+                local remote_checksum;
+                local local_checksum;
+                remote_checksum="$(ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" '{ cat "${temp_dir}/stdout" "${temp_dir}/stderr" && touch "${temp_dir}/output_concat_good"; } | cksum && test -f "${temp_dir}/output_concat_good"')";
+                call_result=$?;
+                if [ "${call_result}" = 255 ]; then
                     continue;
+                else
+                    if [ "${call_result}" != 0 ]; then
+                        softfail "Unable to obtain checksums from remote";
+                        return 1;
+                    fi;
                 fi;
-            fi;
-            task_status="$(ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'cat "${temp_dir}/exit_status"')";
-            call_result=$?;
-            if [ "${call_result}" = 255 ]; then
-                continue;
-            else
-                if [ "${call_result}" != 0 ]; then
-                    softfail "Unable to obtain exit status from remote";
+                local_checksum="$(cat "${temp_dir}/stdout" "${temp_dir}/stderr" | cksum; test "${PIPESTATUS[*]}" = "0 0")" || softfail "Unable to get local output checksum" || return $?;
+                if [ "${remote_checksum}" != "${local_checksum}" ]; then
+                    softfail "Output checksum mismatch";
                     return 1;
                 fi;
+                break;
+            done;
+            local error_state=false;
+            if [ -s "${temp_dir}/stdout" ]; then
+                cat "${temp_dir}/stdout" || { 
+                    echo "Unable to display task stdout ($?)" 1>&2;
+                    error_state=true
+                };
             fi;
-            if ! [[ "${task_status}" =~ ^[0-9]+$ ]]; then
-                task_status=1;
-            fi;
-            task_status_retrieved=true;
-        fi;
-        if [ "${stdout_retrieved}" = false ]; then
-            ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'cat "${temp_dir}/stdout"' > "${temp_dir}/stdout";
-            call_result=$?;
-            if [ "${call_result}" = 255 ]; then
-                continue;
-            else
-                if [ "${call_result}" != 0 ]; then
-                    softfail "Unable to obtain stdout from remote";
-                    return 1;
+            if [ -s "${temp_dir}/stderr" ]; then
+                local terminal_sequence;
+                if [ -t 2 ] && terminal_sequence="$(tput setaf 1 2>/dev/null)"; then
+                    echo -n "${terminal_sequence}" 1>&2;
+                fi;
+                cat "${temp_dir}/stderr" 1>&2 || { 
+                    echo "Unable to display task stderr ($?)" 1>&2;
+                    error_state=true
+                };
+                if [ -t 2 ] && terminal_sequence="$(tput sgr 0 2>/dev/null)"; then
+                    echo -n "${terminal_sequence}" 1>&2;
                 fi;
             fi;
-            stdout_retrieved=true;
-        fi;
-        if [ "${stderr_retrieved}" = false ]; then
-            ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'cat "${temp_dir}/stderr"' > "${temp_dir}/stderr";
-            call_result=$?;
-            if [ "${call_result}" = 255 ]; then
-                continue;
-            else
-                if [ "${call_result}" != 0 ]; then
-                    softfail "Unable to obtain stderr from remote";
-                    return 1;
-                fi;
-            fi;
-            stderr_retrieved=true;
-        fi;
-        local remote_checksum;
-        local local_checksum;
-        remote_checksum="$(ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" '{ cat "${temp_dir}/stdout" "${temp_dir}/stderr" && touch "${temp_dir}/output_concat_good"; } | cksum && test -f "${temp_dir}/output_concat_good"')";
-        call_result=$?;
-        if [ "${call_result}" = 255 ]; then
-            continue;
-        else
-            if [ "${call_result}" != 0 ]; then
-                softfail "Unable to obtain checksums from remote";
+            if [ "${error_state}" = true ]; then
+                softfail "Error reading STDOUT/STDERR in ssh::call";
                 return 1;
             fi;
         fi;
-        local_checksum="$(cat "${temp_dir}/stdout" "${temp_dir}/stderr" | cksum; test "${PIPESTATUS[*]}" = "0 0")" || softfail "Unable to get local output checksum" || return $?;
-        if [ "${remote_checksum}" != "${local_checksum}" ]; then
-            softfail "Output checksum mismatch";
-            return 1;
-        fi;
-        break;
-    done;
-    local error_state=false;
-    if [ -s "${temp_dir}/stdout" ]; then
-        cat "${temp_dir}/stdout" || { 
-            echo "Unable to display task stdout ($?)" 1>&2;
-            error_state=true
-        };
-    fi;
-    if [ -s "${temp_dir}/stderr" ]; then
-        local terminal_sequence;
-        if [ -t 2 ] && terminal_sequence="$(tput setaf 1 2>/dev/null)"; then
-            echo -n "${terminal_sequence}" 1>&2;
-        fi;
-        cat "${temp_dir}/stderr" 1>&2 || { 
-            echo "Unable to display task stderr ($?)" 1>&2;
-            error_state=true
-        };
-        if [ -t 2 ] && terminal_sequence="$(tput sgr 0 2>/dev/null)"; then
-            echo -n "${terminal_sequence}" 1>&2;
-        fi;
-    fi;
-    if [ "${error_state}" = true ]; then
-        softfail "Error reading STDOUT/STDERR in ssh::call";
-        return 1;
     fi;
     if [ "${keep_temp_files}" != true ]; then
         ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'rm -fd "${temp_dir}/script" "${temp_dir}/stdin" "${temp_dir}/stdout" "${temp_dir}/stderr" "${temp_dir}/output_concat_good" "${temp_dir}/exit_status" "${temp_dir}/done" "${temp_dir}"';
@@ -473,10 +487,15 @@ ssh::call::interactive_terminal_functions_filter ()
 ssh::call::invoke () 
 { 
     local nohup_mode=false;
+    local terminal_mode;
     while [[ "$#" -gt 0 ]]; do
         case $1 in 
             --nohup)
                 nohup_mode=true;
+                shift
+            ;;
+            --terminal)
+                terminal_mode=true;
                 shift
             ;;
             -*)
@@ -497,7 +516,7 @@ ssh::call::invoke ()
     if [ "${nohup_mode}" = true ]; then
         command_string="$(printf "nohup sh -c %q >/dev/null 2>/dev/null </dev/null" "${command_string}")";
     fi;
-    ssh "${Ssh_Args[@]}" "${ssh_destination}" "$(printf "sh -c %q" "${command_string}")"
+    ssh ${terminal_mode:+"-t"} "${Ssh_Args[@]}" "${ssh_destination}" "$(printf "sh -c %q" "${command_string}")"
 }
 
 log::message () 
