build
Signed-off-by: Stanislav Senotrusov <senotrusov@gmail.com>

diff --git a/dist/runag b/dist/runag
--- a/dist/runag
+++ b/dist/runag
@@ -777,7 +777,7 @@ file::get_block ()
     local file_path="$1";
     local block_name="$2";
     if [ -f "${file_path}" ]; then
-        test "$(<"${file_path}" sed -n "/^# BEGIN ${block_name}$/,/^# END ${block_name}$/p" | tail -n +2 | head -n -1 | wc -l)" -ge 1 || softfail "Block ${block_name} not found in ${file_path}" || return $?;
+        test "$(sed -n "/^# BEGIN ${block_name}$/,/^# END ${block_name}$/p" < "${file_path}" | tail -n +2 | head -n -1 | wc -l)" -ge 1 || softfail "Block ${block_name} not found in ${file_path}" || return $?;
         sed -n "/^# BEGIN ${block_name}$/,/^# END ${block_name}$/p" < "${file_path}" | tail -n +2 | head -n -1;
         test "${PIPESTATUS[*]}" = "0 0 0" || softfail || return $?;
     fi
@@ -1076,7 +1076,7 @@ fs::get_absolute_path ()
     local unresolved_dir;
     unresolved_dir="$(dirname "${relative_path}")" || softfail "Unable to get a dirname of '${relative_path}'" || return $?;
     local resolved_dir;
-    resolved_dir="$(cd "${unresolved_dir}" >/dev/null 2>&1 && pwd)" || softfail "Unable to determine absolute path for '${unresolved_dir}'" || return $?;
+    resolved_dir="$(cd "${unresolved_dir}" > /dev/null 2>&1 && pwd)" || softfail "Unable to determine absolute path for '${unresolved_dir}'" || return $?;
     echo "${resolved_dir}/${path_basename}"
 }
 fs::update_symlink () 
@@ -1129,7 +1129,7 @@ fstab::add_mount_option ()
     done;
     local option="$1";
     local skip;
-    skip="$(<<<"${option}" sed 's/^\([[:alnum:]]\+\).*/\1/')" || softfail || return $?;
+    skip="$(sed 's/^\([[:alnum:]]\+\).*/\1/' <<< "${option}")" || softfail || return $?;
     sed "/^\(#\|[[:graph:]]\+[[:blank:]]\+[[:graph:]]\+[[:blank:]]\+${fstype}[[:blank:]]\+.*[[:blank:][:punct:]]${skip}\([[:blank:][:punct:]]\|$\)\)/!s/^\([[:graph:]]\+[[:blank:]]\+[[:graph:]]\+[[:blank:]]\+${fstype}[[:blank:]]\+defaults\)\([^[:alnum:]]\|$\)/\1,${option}\2/g;" /etc/fstab | fstab::verify_and_write;
     test "${PIPESTATUS[*]}" = "0 0" || softfail "Error adding mount option to /etc/fstab" || return $?
 }
@@ -1317,7 +1317,7 @@ git::remove_current_clone ()
 { 
     local dest_path="$1";
     local dest_full_path;
-    dest_full_path="$(cd "${dest_path}" >/dev/null 2>&1 && pwd)" || softfail || return $?;
+    dest_full_path="$(cd "${dest_path}" > /dev/null 2>&1 && pwd)" || softfail || return $?;
     local dest_parent_dir;
     dest_parent_dir="$(dirname "${dest_full_path}")" || softfail || return $?;
     local dest_dir_name;
@@ -1477,9 +1477,9 @@ gpg::import_key ()
     fi;
     if [ "${should_confirm:-}" = true ]; then
         local key_with_spaces;
-        key_with_spaces="$(<<<"${gpg_key_id}" sed -E 's/(.{4})/\1 /g' | sed 's/ $//'; test "${PIPESTATUS[*]}" = "0 0")" || softfail || return $?;
+        key_with_spaces="$(sed -E 's/(.{4})/\1 /g' <<< "${gpg_key_id}" | sed 's/ $//'; test "${PIPESTATUS[*]}" = "0 0")" || softfail || return $?;
         local key_base64;
-        key_base64="$(<<<"${gpg_key_id}" xxd -r -p | base64 | sed -E 's/(.{4})/\1 /g' | sed 's/ $//'; test "${PIPESTATUS[*]}" = "0 0 0 0")" || softfail || return $?;
+        key_base64="$(xxd -r -p <<< "${gpg_key_id}" | base64 | sed -E 's/(.{4})/\1 /g' | sed 's/ $//'; test "${PIPESTATUS[*]}" = "0 0 0 0")" || softfail || return $?;
         echo "";
         echo "You are about to import GPG key with id: ${gpg_key_id}.";
         if [ -n "${trust_level:-}" ]; then
@@ -1601,7 +1601,7 @@ leaseweb::domains::set_record ()
         fi;
     fi;
     local domain_exists;
-    domain_exists="$(curl     --header "X-Lsw-Auth: ${LEASEWEB_API_KEY}"     --output /dev/null     --request GET     --show-error     --silent     --url "https://api.leaseweb.com/hosting/v2/domains/${domain}/resourceRecordSets/${record}./${record_type}"     --write-out "%{http_code}"     )" || softfail || return $?;
+    domain_exists="$(curl --header "X-Lsw-Auth: ${LEASEWEB_API_KEY}" --output /dev/null --request GET --show-error --silent --url "https://api.leaseweb.com/hosting/v2/domains/${domain}/resourceRecordSets/${record}./${record_type}" --write-out "%{http_code}")" || softfail || return $?;
     if [ "${domain_exists}" = 200 ]; then
         curl --data "{ \"content\": [\"${record_data}\"], \"ttl\": ${record_ttl} }" --fail --header "content-type: application/json" --header "X-Lsw-Auth: ${LEASEWEB_API_KEY}" --output /dev/null --request PUT --show-error --silent --url "https://api.leaseweb.com/hosting/v2/domains/${domain}/resourceRecordSets/${record}./${record_type}" || softfail || return $?;
     else
@@ -1670,7 +1670,7 @@ EOF
 linux::get_cpu_count () 
 { 
     local cpu_count;
-    cpu_count="$(grep -c ^processor /proc/cpuinfo 2>/dev/null)";
+    cpu_count="$(grep -c ^processor /proc/cpuinfo 2> /dev/null)";
     if [[ "${cpu_count}" =~ ^[0-9]+$ ]]; then
         echo "${cpu_count}";
     else
@@ -1695,7 +1695,7 @@ linux::get_home_dir ()
 linux::get_ipv4_address () 
 { 
     local ip_address;
-    ip_address="$(ip route get 1.1.1.1 2>/dev/null | sed -n 's/^.*src \([[:digit:].]*\).*$/\1/p'; test "${PIPESTATUS[*]}" = "0 0")" || softfail "Unable to obtain host ipv6 address" || return $?;
+    ip_address="$(ip route get 1.1.1.1 2> /dev/null | sed -n 's/^.*src \([[:digit:].]*\).*$/\1/p'; test "${PIPESTATUS[*]}" = "0 0")" || softfail "Unable to obtain host ipv6 address" || return $?;
     if [ -z "${ip_address}" ]; then
         softfail "Unable to obtain host ipv6 address" || return $?;
     fi;
@@ -1704,7 +1704,7 @@ linux::get_ipv4_address ()
 linux::get_ipv6_address () 
 { 
     local ip_address;
-    ip_address="$(ip route get 2606:4700:4700::1111 2>/dev/null | sed -n 's/^.*src \([[:xdigit:]:]*\).*$/\1/p'; test "${PIPESTATUS[*]}" = "0 0")" || softfail "Unable to obtain host ipv6 address" || return $?;
+    ip_address="$(ip route get 2606:4700:4700::1111 2> /dev/null | sed -n 's/^.*src \([[:xdigit:]:]*\).*$/\1/p'; test "${PIPESTATUS[*]}" = "0 0")" || softfail "Unable to obtain host ipv6 address" || return $?;
     if [ -z "${ip_address}" ]; then
         softfail "Unable to obtain host ipv6 address" || return $?;
     fi;
@@ -1745,7 +1745,7 @@ linux::reset_locales ()
     do
         if [[ "${item}" =~ ^[[:alpha:]_]+=(.*)$ ]]; then
             local locale_match;
-            locale_match="$(<<<"${BASH_REMATCH[1]}" sed -E 's/[.]/[.]/g')" || softfail || return $?;
+            locale_match="$(sed -E 's/[.]/[.]/g' <<< "${BASH_REMATCH[1]}")" || softfail || return $?;
             sudo sed --in-place -E 's/^# ('"${locale_match}"' )/\1/g' /etc/locale.gen || softfail || return $?;
         fi;
     done;
@@ -1824,7 +1824,7 @@ linux::set_hostname ()
         return 0;
     fi;
     local previous_name_escaped;
-    previous_name_escaped="$(<<<"${previous_name}" sed 's/\./\\./g')" || softfail || return $?;
+    previous_name_escaped="$(sed 's/\./\\./g' <<< "${previous_name}")" || softfail || return $?;
     file::append_line_unless_present --sudo --keep-permissions --mode 0644 "${hosts_file}" "127.0.1.1	${new_name}" || softfail || return $?;
     sudo hostnamectl set-hostname "${new_name}" || softfail || return $?;
     local temp_file;
@@ -1866,7 +1866,7 @@ log::error ()
 { 
     local message="${1:-"(empty log message)"}";
     if [ -t 2 ]; then
-        echo "$(printf "setaf 9\nbold" | tput -S 2>/dev/null)${message}$(tput sgr 0 2>/dev/null)" 1>&2;
+        echo "$(printf "setaf 9\nbold" | tput -S 2> /dev/null)${message}$(tput sgr 0 2> /dev/null)" 1>&2;
     else
         echo "[ERROR] ${message}" 1>&2;
     fi
@@ -1883,7 +1883,7 @@ log::notice ()
 { 
     local message="${1:-"(empty log message)"}";
     if [ -t 2 ]; then
-        echo "$(printf "setaf 14\nbold" | tput -S 2>/dev/null)${message}$(tput sgr 0 2>/dev/null)" 1>&2;
+        echo "$(printf "setaf 14\nbold" | tput -S 2> /dev/null)${message}$(tput sgr 0 2> /dev/null)" 1>&2;
     else
         echo "[NOTICE] ${message}" 1>&2;
     fi
@@ -1892,7 +1892,7 @@ log::success ()
 { 
     local message="${1:-"(empty log message)"}";
     if [ -t 2 ]; then
-        echo "$(printf "setaf 13\nbold" | tput -S 2>/dev/null)${message}$(tput sgr 0 2>/dev/null)" 1>&2;
+        echo "$(printf "setaf 13\nbold" | tput -S 2> /dev/null)${message}$(tput sgr 0 2> /dev/null)" 1>&2;
     else
         echo "[SUCCESS] ${message}" 1>&2;
     fi
@@ -1901,7 +1901,7 @@ log::warning ()
 { 
     local message="${1:-"(empty log message)"}";
     if [ -t 2 ]; then
-        echo "$(printf "setaf 11\nbold" | tput -S 2>/dev/null)${message}$(tput sgr 0 2>/dev/null)" 1>&2;
+        echo "$(printf "setaf 11\nbold" | tput -S 2> /dev/null)${message}$(tput sgr 0 2> /dev/null)" 1>&2;
     else
         echo "[WARNING] ${message}" 1>&2;
     fi
@@ -1954,10 +1954,9 @@ macos::install_homebrew ()
 }
 nodejs::install::apt () 
 { 
-    ( local version="$1";
-    . /etc/os-release || softfail || return $?;
-    apt::add_source_with_key "nodesource" "https://deb.nodesource.com/node_${version}.x ${VERSION_CODENAME} main" "https://deb.nodesource.com/gpgkey/nodesource.gpg.key" || softfail || return $?;
-    apt::install nodejs || softfail || return $? )
+    local version="$1";
+    apt::add_source_with_key "nodesource" "https://deb.nodesource.com/node_${version}.x nodistro main" "https://deb.nodesource.com/gpgkey/nodesource.gpg.key" || softfail || return $?;
+    apt::install nodejs || softfail || return $?
 }
 nodejs::install_dependencies::apt () 
 { 
@@ -2046,10 +2045,10 @@ pass::get_metadata ()
 { 
     local match_string="$1";
     local match_string_canonical;
-    match_string_canonical="$(<<<"${match_string}" tr "[:upper:]" "[:lower:]" | sed "s/^[[:blank:]]*//;s/[[:blank:]]*$//"; test "${PIPESTATUS[*]}" = "0 0")" || softfail "Unable to produce match_string_canonical" || return $?;
+    match_string_canonical="$(tr "[:upper:]" "[:lower:]" <<< "${match_string}" | sed "s/^[[:blank:]]*//;s/[[:blank:]]*$//"; test "${PIPESTATUS[*]}" = "0 0")" || softfail "Unable to produce match_string_canonical" || return $?;
     local line metadata_key;
     while IFS="" read -r line; do
-        metadata_key="$(<<<"${line}" tr "[:upper:]" "[:lower:]" | cut -s -d ":" -f 1 | sed "s/^[[:blank:]]*//;s/[[:blank:]]*$//"; test "${PIPESTATUS[*]}" = "0 0 0")" || softfail "Unable to produce canonical metadata_key" || return $?;
+        metadata_key="$(tr "[:upper:]" "[:lower:]" <<< "${line}" | cut -s -d ":" -f 1 | sed "s/^[[:blank:]]*//;s/[[:blank:]]*$//"; test "${PIPESTATUS[*]}" = "0 0 0")" || softfail "Unable to produce canonical metadata_key" || return $?;
         if [ "${metadata_key}" = "${match_string_canonical}" ]; then
             cut -s -d ":" -f 2- <<< "${line}" | sed "s/^[[:blank:]]*//;s/[[:blank:]]*$//";
             test "${PIPESTATUS[*]}" = "0 0" || softfail "Unable to produce metadata value" || return $?;
@@ -2071,7 +2070,7 @@ pass::secret_exists ()
 pass::set_password_store_dir () 
 { 
     local dir_path="$1";
-    dir_path="$(cd "${dir_path}" >/dev/null 2>&1 && pwd)" || softfail || return $?;
+    dir_path="$(cd "${dir_path}" > /dev/null 2>&1 && pwd)" || softfail || return $?;
     export PASSWORD_STORE_DIR="${dir_path}"
 }
 pass::use () 
@@ -2669,7 +2668,7 @@ rsync::rsh_string ()
     local ssh_arg;
     for ssh_arg in "${Ssh_Args[@]}";
     do
-        rsh_string+=" '$(<<<"${ssh_arg}" sed -E "s/'/''/")'" || softfail || return $?;
+        rsh_string+=" '$(sed -E "s/'/''/" <<< "${ssh_arg}")'" || softfail || return $?;
     done;
     echo "ssh ${rsh_string:1}" || softfail || return $?
 }
@@ -2937,9 +2936,9 @@ runag::update_current_offline_install_if_connected ()
 runagfile::add () 
 { 
     local user_name;
-    user_name="$(<<<"$1" cut -d "/" -f 1)" || softfail || return $?;
+    user_name="$(cut -d "/" -f 1 <<< "$1")" || softfail || return $?;
     local repo_name;
-    repo_name="$(<<<"$1" cut -d "/" -f 2)" || softfail || return $?;
+    repo_name="$(cut -d "/" -f 2 <<< "$1")" || softfail || return $?;
     git::place_up_to_date_clone "https://github.com/${user_name}/${repo_name}.git" "${HOME}/.runag/runagfiles/${repo_name}-${user_name}-github" || softfail || return $?
 }
 runagfile::add_from_list () 
@@ -3731,7 +3730,7 @@ ssh::call::internal ()
     local upload_basename;
     if [ -n "${upload_path:-}" ]; then
         if [ -d "${upload_path}" ]; then
-            resolved_upload_path="$(cd "${upload_path}" >/dev/null 2>&1 && pwd)" || softfail "Unable to resolve upload directory: ${upload_path}" || return $?;
+            resolved_upload_path="$(cd "${upload_path}" > /dev/null 2>&1 && pwd)" || softfail "Unable to resolve upload directory: ${upload_path}" || return $?;
             upload_basename="$(basename "${resolved_upload_path}")" || softfail || return $?;
             if [ "${upload_basename}" = "/" ]; then
                 upload_basename=root;
@@ -3746,18 +3745,18 @@ ssh::call::internal ()
         local ssh_args_item;
         for ssh_args_item in "${Ssh_Args[@]}";
         do
-            rsync_ssh_args_string+=" '$(<<<"${ssh_args_item}" sed -E "s/'/''/")'" || softfail || return $?;
+            rsync_ssh_args_string+=" '$(sed -E "s/'/''/" <<< "${ssh_args_item}")'" || softfail || return $?;
         done;
         rsync --rsh "ssh ${rsync_ssh_args_string:1}" --checksum --links --perms --recursive --safe-links --times "${upload_rsync_src}" "${ssh_destination}:${upload_rsync_dest}" || softfail || return $?;
         set -- "$@" "${upload_rsync_dest}";
     fi;
     local script_checksum;
     ssh::call::produce_script "${produce_script_args[@]}" "$@" > "${temp_dir}/script" || softfail "Unable to produce script" || return $?;
-    script_checksum="$(cksum <"${temp_dir}/script")" || softfail "Unable to calculate script checksum" || return $?;
+    script_checksum="$(cksum < "${temp_dir}/script")" || softfail "Unable to calculate script checksum" || return $?;
     local script_upload_command;
     printf -v script_upload_command 'temp_dir="$(mktemp -d)" && cat>"${temp_dir}/script" && { if [ "$(cksum <"${temp_dir}/script")" != %q ]; then exit 254; fi; } && echo "${temp_dir}"' "${script_checksum}" || softfail || return $?;
     local remote_temp_dir;
-    remote_temp_dir="$(ssh "${Ssh_Args[@]}" "${ssh_destination}" "$(printf "sh -c %q" "${script_upload_command}")" <"${temp_dir}/script")" || softfail --exit-status $? "Unable to upload script" || return $?;
+    remote_temp_dir="$(ssh "${Ssh_Args[@]}" "${ssh_destination}" "$(printf "sh -c %q" "${script_upload_command}")" < "${temp_dir}/script")" || softfail --exit-status $? "Unable to upload script" || return $?;
     if [ -z "${remote_temp_dir}" ]; then
         softfail "Unable to get remote temp file name" || return $?;
     fi;
@@ -3778,7 +3777,7 @@ ssh::call::internal ()
                 fi;
                 if [ -s "${temp_dir}/stdin" ]; then
                     local stdin_checksum;
-                    stdin_checksum="$(cksum <"${temp_dir}/stdin")" || softfail "Unable to get stdin checksum" || return $?;
+                    stdin_checksum="$(cksum < "${temp_dir}/stdin")" || softfail "Unable to get stdin checksum" || return $?;
                     ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'cat >"${temp_dir}/stdin"; if [ "$(cksum <"${temp_dir}/stdin")" != %q ]; then exit 254; fi' "${stdin_checksum}" < "${temp_dir}/stdin" || softfail --exit-status $? "Unable to store stdin data on remote" || return $?;
                     remote_stdin_file="${remote_temp_dir}/stdin";
                 fi;
@@ -3898,9 +3897,9 @@ ssh::call::internal ()
             if [ -s "${temp_dir}/stderr" ]; then
                 if test -t 2; then
                     local error_color;
-                    error_color="$(printf "setaf 9\nbold" | tput -S 2>/dev/null)" || error_color="";
+                    error_color="$(printf "setaf 9\nbold" | tput -S 2> /dev/null)" || error_color="";
                     local reset_attrs;
-                    reset_attrs="$(tput sgr 0 2>/dev/null)" || reset_attrs="";
+                    reset_attrs="$(tput sgr 0 2> /dev/null)" || reset_attrs="";
                     local error_line;
                     while IFS="" read -r error_line; do
                         echo "${error_color}${error_line}${reset_attrs}" 1>&2;
@@ -4391,7 +4390,7 @@ ssh::wait_for_host_to_become_available ()
     local host_name="${1:-"${REMOTE_HOST}"}";
     while true; do
         local key;
-        key="$(ssh-keyscan -p "${ssh_port}" "${host_name}" 2>/dev/null)";
+        key="$(ssh-keyscan -p "${ssh_port}" "${host_name}" 2> /dev/null)";
         if [ -n "${key}" ]; then
             return 0;
         else
@@ -5029,19 +5028,19 @@ task::display ()
     local Clear_Line="";
     local Leading_Spacer=" ";
     if [ -t 0 ]; then
-        Prompt_Color="$(printf "setaf 11\nbold" | tput -S 2>/dev/null)" || Prompt_Color="";
+        Prompt_Color="$(printf "setaf 11\nbold" | tput -S 2> /dev/null)" || Prompt_Color="";
     fi;
     if [ -t 1 ]; then
-        Color_A="$(tput setaf 9 2>/dev/null)" || Color_A="";
-        Color_A_Accent="$(printf "setaf 15\nsetab 9" | tput -S 2>/dev/null)" || Color_A_Accent="";
-        Color_B_Accent="$(printf "setaf 15\nsetab 8" | tput -S 2>/dev/null)" || Color_B_Accent="";
-        Header_Color="$(printf "setaf 14\nbold" | tput -S 2>/dev/null)" || Header_Color="";
-        Comment_Color="$(printf "setaf 13\nbold" | tput -S 2>/dev/null)" || Comment_Color="";
-        Cursor_Up_Seq="$(tput cuu1 2>/dev/null)" || softfail || return $?;
+        Color_A="$(tput setaf 9 2> /dev/null)" || Color_A="";
+        Color_A_Accent="$(printf "setaf 15\nsetab 9" | tput -S 2> /dev/null)" || Color_A_Accent="";
+        Color_B_Accent="$(printf "setaf 15\nsetab 8" | tput -S 2> /dev/null)" || Color_B_Accent="";
+        Header_Color="$(printf "setaf 14\nbold" | tput -S 2> /dev/null)" || Header_Color="";
+        Comment_Color="$(printf "setaf 13\nbold" | tput -S 2> /dev/null)" || Comment_Color="";
+        Cursor_Up_Seq="$(tput cuu1 2> /dev/null)" || softfail || return $?;
     fi;
     if [ -t 0 ] || [ -t 1 ]; then
-        Reset_Attrs="$(tput sgr 0 2>/dev/null)" || softfail || return $?;
-        Clear_Line="$(tput el 2>/dev/null)" || softfail || return $?;
+        Reset_Attrs="$(tput sgr 0 2> /dev/null)" || softfail || return $?;
+        Clear_Line="$(tput el 2> /dev/null)" || softfail || return $?;
     fi;
     local Item_Position=undefined;
     local Section_Position=undefined;
diff --git a/dist/ssh-call b/dist/ssh-call
--- a/dist/ssh-call
+++ b/dist/ssh-call
@@ -234,7 +234,7 @@ ssh::call::internal ()
     local upload_basename;
     if [ -n "${upload_path:-}" ]; then
         if [ -d "${upload_path}" ]; then
-            resolved_upload_path="$(cd "${upload_path}" >/dev/null 2>&1 && pwd)" || softfail "Unable to resolve upload directory: ${upload_path}" || return $?;
+            resolved_upload_path="$(cd "${upload_path}" > /dev/null 2>&1 && pwd)" || softfail "Unable to resolve upload directory: ${upload_path}" || return $?;
             upload_basename="$(basename "${resolved_upload_path}")" || softfail || return $?;
             if [ "${upload_basename}" = "/" ]; then
                 upload_basename=root;
@@ -249,18 +249,18 @@ ssh::call::internal ()
         local ssh_args_item;
         for ssh_args_item in "${Ssh_Args[@]}";
         do
-            rsync_ssh_args_string+=" '$(<<<"${ssh_args_item}" sed -E "s/'/''/")'" || softfail || return $?;
+            rsync_ssh_args_string+=" '$(sed -E "s/'/''/" <<< "${ssh_args_item}")'" || softfail || return $?;
         done;
         rsync --rsh "ssh ${rsync_ssh_args_string:1}" --checksum --links --perms --recursive --safe-links --times "${upload_rsync_src}" "${ssh_destination}:${upload_rsync_dest}" || softfail || return $?;
         set -- "$@" "${upload_rsync_dest}";
     fi;
     local script_checksum;
     ssh::call::produce_script "${produce_script_args[@]}" "$@" > "${temp_dir}/script" || softfail "Unable to produce script" || return $?;
-    script_checksum="$(cksum <"${temp_dir}/script")" || softfail "Unable to calculate script checksum" || return $?;
+    script_checksum="$(cksum < "${temp_dir}/script")" || softfail "Unable to calculate script checksum" || return $?;
     local script_upload_command;
     printf -v script_upload_command 'temp_dir="$(mktemp -d)" && cat>"${temp_dir}/script" && { if [ "$(cksum <"${temp_dir}/script")" != %q ]; then exit 254; fi; } && echo "${temp_dir}"' "${script_checksum}" || softfail || return $?;
     local remote_temp_dir;
-    remote_temp_dir="$(ssh "${Ssh_Args[@]}" "${ssh_destination}" "$(printf "sh -c %q" "${script_upload_command}")" <"${temp_dir}/script")" || softfail --exit-status $? "Unable to upload script" || return $?;
+    remote_temp_dir="$(ssh "${Ssh_Args[@]}" "${ssh_destination}" "$(printf "sh -c %q" "${script_upload_command}")" < "${temp_dir}/script")" || softfail --exit-status $? "Unable to upload script" || return $?;
     if [ -z "${remote_temp_dir}" ]; then
         softfail "Unable to get remote temp file name" || return $?;
     fi;
@@ -281,7 +281,7 @@ ssh::call::internal ()
                 fi;
                 if [ -s "${temp_dir}/stdin" ]; then
                     local stdin_checksum;
-                    stdin_checksum="$(cksum <"${temp_dir}/stdin")" || softfail "Unable to get stdin checksum" || return $?;
+                    stdin_checksum="$(cksum < "${temp_dir}/stdin")" || softfail "Unable to get stdin checksum" || return $?;
                     ssh::call::invoke "${remote_temp_dir}" "${ssh_destination}" 'cat >"${temp_dir}/stdin"; if [ "$(cksum <"${temp_dir}/stdin")" != %q ]; then exit 254; fi' "${stdin_checksum}" < "${temp_dir}/stdin" || softfail --exit-status $? "Unable to store stdin data on remote" || return $?;
                     remote_stdin_file="${remote_temp_dir}/stdin";
                 fi;
@@ -401,9 +401,9 @@ ssh::call::internal ()
             if [ -s "${temp_dir}/stderr" ]; then
                 if test -t 2; then
                     local error_color;
-                    error_color="$(printf "setaf 9\nbold" | tput -S 2>/dev/null)" || error_color="";
+                    error_color="$(printf "setaf 9\nbold" | tput -S 2> /dev/null)" || error_color="";
                     local reset_attrs;
-                    reset_attrs="$(tput sgr 0 2>/dev/null)" || reset_attrs="";
+                    reset_attrs="$(tput sgr 0 2> /dev/null)" || reset_attrs="";
                     local error_line;
                     while IFS="" read -r error_line; do
                         echo "${error_color}${error_line}${reset_attrs}" 1>&2;
@@ -632,7 +632,7 @@ log::notice ()
 { 
     local message="${1:-"(empty log message)"}";
     if [ -t 2 ]; then
-        echo "$(printf "setaf 14\nbold" | tput -S 2>/dev/null)${message}$(tput sgr 0 2>/dev/null)" 1>&2;
+        echo "$(printf "setaf 14\nbold" | tput -S 2> /dev/null)${message}$(tput sgr 0 2> /dev/null)" 1>&2;
     else
         echo "[NOTICE] ${message}" 1>&2;
     fi
