build
Signed-off-by: Stanislav Senotrusov <senotrusov@gmail.com>

diff --git a/dist/runag b/dist/runag
--- a/dist/runag
+++ b/dist/runag
@@ -3336,6 +3336,25 @@ fi
 SHELL
  softfail || return $?
 }
+shellfile::install_fzf_rc () 
+{ 
+    local license_text;
+    license_text="$(runag::print_license)" || softfail || return $?;
+    shellfile::write "$@" "rc/fzf" <<SHELL || 
+${license_text}
+
+export FZF_DEFAULT_OPTS="--exact"
+
+if command -v fzf >/dev/null; then
+  if [ -n "\${ZSH_VERSION:-}" ]; then
+    source <(fzf --zsh) || echo "Unable to hook fzf" >&2
+  elif [ -n "\${BASH_VERSION:-}" ]; then
+    eval "\$(fzf --bash)" || echo "Unable to hook fzf" >&2
+  fi
+fi
+SHELL
+ softfail || return $?
+}
 shellfile::install_loader::bash () 
 { 
     shellfile::write_loader_block --file "${HOME}/.bashrc" --dir ".shellfile.d/rc" || softfail || return $?;
